spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: sedman144@gmail.com
    password: xtrv wdcj rgvy dcbf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083