server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projects
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/master
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.transaction.interceptor: TRACE
services:
  user-service-url: http://localhost:8080/api/user